Repository WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b, pull requests merged in 2023-11, with the labels that each got.

#44 Feature/404 page
  public/link404.png
  public/sad.png
  src/components/Error404.jsx
  src/router.jsx
Labels: Sylvain

#41 add picture to gameshow
  src/components/gameshow/CarouselGameShow.jsx
  src/components/gameshow/Description.jsx
  src/components/gameshow/GameShow.jsx
  src/components/gameshow/HeaderGameShow.jsx
  src/components/gameshow/Thumbnails.jsx
Labels: Sylvain, Correction done

#43 create about the team page
  public/images/Cedric.webp
  public/images/Herve.webp
  public/images/Melvin.webp
  public/images/Mike.webp
  src/components/AboutTheTeam.jsx
  src/components/Footer.jsx
  src/components/logos/LogoLinkedin.jsx
  src/components/logos/logo-linkedin.svg
  src/router.jsx
Labels: Sylvain, Correction done

#48 Ajout RatingComments & fix GameShow & RatingBox
  src/components/Retro/Cube3D.jsx
  src/components/Retro/RetroContainer.jsx
  src/components/gameshow/DlcComponent.jsx
  src/components/gameshow/GameShow.jsx
  src/components/gameshow/RatingBox.jsx
  src/components/gameshow/RatingComments.jsx
  src/components/gameshow/RightBar.jsx
  src/components/genres/CarouselCard.jsx
  src/components/home/CarouselHome.jsx
  tailwind.config.js
Labels: Sylvain, Correction done

#37 Feature/achievements reworked
  src/components/gameshow/AchievementTooltip.jsx
  src/components/gameshow/Achievements.jsx
  src/components/gameshow/GameShow.jsx
Labels: Sylvain

#50 Feature/search games
  public/images/placeholder.webp
  src/App.css
  src/App.jsx
  src/components/MiniLogo.jsx
  src/components/Spinner.jsx
  src/components/home/Home.jsx
  src/components/home/PlatformsList.jsx
  src/components/home/PlatformsLogo.jsx
  src/components/icons/IconMagnifyingGlass.jsx
  src/components/logos/LogoAtari.jsx
  src/components/logos/LogoCommodor.jsx
  src/components/logos/LogoDreamcast.jsx
  src/components/logos/LogoLinux.jsx
  src/components/logos/LogoNeoGeo.jsx
  src/components/logos/LogoSega.jsx
  src/components/search/CardGame.jsx
  src/components/search/Search.jsx
  src/components/search/SearchBar.jsx
  src/hooks/useGameSearch.js
  src/router.jsx
Labels: Sylvain, Correction done

#46 Feature/fix rightbar
  public/googleplay.png
  public/itch-io.png
  src/components/gameshow/RightBar.jsx
  src/components/gameshow/StoreLogo.jsx
Labels: Sylvain, Correction done

#51 Feature/fix retro
  src/App.css
  src/components/Retro/Cube3D.jsx
  src/components/Retro/RetroContainer.jsx
  src/components/Retro/Top10List.jsx
Labels: Sylvain

#57 fixe cedrick
  src/App.css
  src/components/AboutTheTeam.jsx
  src/components/Retro/Cube3D.jsx
  src/components/Retro/RetroContainer.jsx
  src/components/Retro/Top10List.jsx
  src/components/gameshow/GameShow.jsx
  src/components/gameshow/ProgressBar.jsx
  src/components/gameshow/RatingBox.jsx
  src/components/gameshow/RatingComments.jsx
Labels: Review

#58 Feature/fix gameshow
  public/separator.png
  src/App.jsx
  src/components/Title.jsx
  src/components/gameshow/Achievements.jsx
  src/components/gameshow/Description.jsx
  src/components/gameshow/DlcComponent.jsx
  src/components/gameshow/GameShow.jsx
  src/components/gameshow/PlatformLogo.jsx
  src/components/gameshow/ReadMore.jsx
  src/components/gameshow/RightBar.jsx
  src/components/home/PlatformsList.jsx
Labels: Review

#59 Feature/fix remove btn
  src/components/home/Home.jsx
Labels: Review

#60 Feature/fix warning
  src/components/genres/Carousel.jsx
Labels: Review

#84 fixe link
  src/components/AboutTheTeam.jsx
Labels: Sylvain
