Repository WildCodeSchool/2023-09-orleans-cda-projet1-groupe-b, pull requests merged in 2023-10, with the labels that each got.

#1 initialisation
  package-lock.json
  package.json
  postcss.config.js
  public/fonts/GalakPro-Bold.otf
  public/fonts/GalakPro-Heavy.otf
  public/fonts/GalakPro-Light.otf
  public/fonts/GalakPro-Medium.otf
  src/App.css
  src/App.jsx
  src/style/fonts.css
  tailwind.config.js
  vite.config.prod.js
Labels: Sylvain, Correction done

#5 Feature/api config
  .env.sample
  .gitignore
  src/App.css
  src/api/api-fetch.js
  src/api/api-url.js
  tailwind.config.js
Labels: Sylvain

#6 Feature/gameshow carousel
  package-lock.json
  public/images/background.jpg
  public/vite.svg
  src/App.jsx
  src/api/api-fetch.js
  src/components/gameshow/CarouselGameShow.jsx
  src/components/gameshow/GameShow.jsx
  src/components/gameshow/NextButton.jsx
  src/components/gameshow/PreviousButton.jsx
  src/components/gameshow/Thumbnails.jsx
  src/components/gameshow/ThumbnailsPaginations.jsx
  src/router.jsx
  src/style/fonts.css
  tailwind.config.js
Labels: Sylvain

#7 Feature/router
  package-lock.json
  src/App.jsx
  src/components/BestSellers.jsx
  src/components/Error404.jsx
  src/components/Home.jsx
  src/components/Navbar.jsx
  src/components/News.jsx
  src/components/Offers.jsx
  src/components/Recommandations.jsx
  src/main.jsx
  src/router.jsx
Labels: Sylvain, Correction done

#8 Feature/home header
  package-lock.json
  package.json
  public/images/jinx.webp
  public/images/kratos.webp
  public/images/logo.svg
  public/images/mario.webp
  public/images/masterchief.webp
  src/App.css
  src/App.jsx
  src/api/api-fetch.js
  src/api/api-url.js
  src/components/Button.jsx
  src/components/Home.jsx
  src/components/Logo.jsx
  src/components/Navbar.jsx
  src/components/gameshow/GameShow.jsx
  src/components/gameshow/Thumbnails.jsx
  src/components/home/HeaderHome.jsx
  src/components/home/Home.jsx
  src/router.jsx
  tailwind.config.js
Labels: Sylvain

#11 fixe fetch methods
  src/api/api-fetch.js
  src/components/gameshow/CarouselGameShow.jsx
  src/components/gameshow/GameShow.jsx
  src/components/gameshow/Thumbnails.jsx
  src/components/home/HeaderHome.jsx
  src/components/home/Home.jsx
  src/router.jsx
Labels: Sylvain

#20 Feature/home the unavoidable
  src/App.jsx
  src/components/Button.jsx
  src/components/Title.jsx
  src/components/home/HeaderHome.jsx
  src/components/home/Home.jsx
  src/components/home/Unavoidable.jsx
  src/components/logos/LogoAndroid.jsx
  src/components/logos/LogoIos.jsx
  src/components/logos/LogoNintendo.jsx
  src/components/logos/LogoPc.jsx
  src/components/logos/LogoPlaystation.jsx
  src/components/logos/LogoXbox.jsx
Labels: Sylvain

#18 Feature/footer
  src/App.jsx
  src/components/Footer.jsx
Labels: Review, Sylvain

#14 Feature/game infos
  package-lock.json
  package.json
  public/196px-PEGI_18.svg.png
  public/197px-PEGI_12.svg.png
  public/197px-PEGI_16.svg.png
  public/197px-PEGI_3.svg.png
  public/android.png
  public/appstore.png
  public/dlc.png
  public/epic-games.png
  public/gog.png
  public/ios.png
  public/linux.png
  public/macos.png
  public/nintendo.png
  public/playstation.png
  public/react.svg
  public/separator.png
  public/steamwh.png
  public/windows.png
  public/xbox.png
  src/App.css
  src/components/gameshow/AgeRatingLogo.jsx
  src/components/gameshow/DlcComponent.jsx
  src/components/gameshow/GameShow.jsx
  src/components/gameshow/PlatformLogo.jsx
  src/components/gameshow/RightBar.jsx
  src/components/gameshow/StoreLogo.jsx
  src/utils/MetascoreColor.js
Labels: Sylvain, Correction done

#12 Feature/categories
  package-lock.json
  src/App.css
  src/App.jsx
  src/components/Navbar.jsx
  src/components/genres/Carousel.jsx
  src/components/genres/CarouselCard.jsx
  src/components/genres/Categories.jsx
  src/components/genres/GridCard.jsx
  src/components/genres/HeaderGenre.jsx
  src/router.jsx
  tailwind.config.js
Labels: Sylvain, Correction done

#15 Feature/game desc and specs
  src/components/gameshow/Description.jsx
  src/components/gameshow/GameShow.jsx
  src/components/gameshow/ReadMore.jsx
  src/utils/TextFormatter.jsx
Labels: Sylvain, Correction done

#24 Feature/scroll top
  package-lock.json
  src/App.jsx
  src/components/ScrollTop.jsx
  src/components/home/Home.jsx
Labels: Sylvain

#25 Feature/add plateform card
  src/components/genres/CarouselCard.jsx
  src/components/genres/GridCard.jsx
Labels: Sylvain

#19 Feature/navbar
  package-lock.json
  public/images/Vector.svg
  public/images/android.svg
  public/images/category.svg
  public/images/controller.svg
  public/images/drop_arrow.svg
  public/images/ios.svg
  public/images/microsoft.svg
  public/images/nintendo.svg
  public/images/playstation.svg
  public/images/recommandation.svg
  public/images/xbox.svg
  src/App.jsx
  src/components/Navbar.jsx
  src/components/NavbarTools/Collapsible.jsx
  src/components/NavbarTools/Dropdown.jsx
  src/components/News.jsx
  src/hooks/useMenuAnimation.jsx
  src/router.jsx
  src/style/fonts.css
  tailwind.config.js
Labels: Sylvain, Correction done

#16 Feature/retro
  package-lock.json
  public/fonts/ARCADE_N.TTF
  public/images/BgCube.svg
  public/images/GPLogodark2.webp
  public/images/GPLogoprim2.webp
  public/images/mario.webp
  src/App.css
  src/api/api-fetch.js
  src/components/Navbar.jsx
  src/components/Retro/Cube3D.jsx
  src/components/Retro/RetroContainer.jsx
  src/components/Retro/Top10List.jsx
  src/components/Title.jsx
  src/components/home/Home.jsx
  src/style/fonts.css
  tailwind.config.js
Labels: Sylvain, Correction done

#26 carousel best game
  src/components/genres/Carousel.jsx
Labels: Sylvain, Correction done

#27 filter
  src/components/genres/CarouselCard.jsx
  src/components/genres/GridCard.jsx
Labels: Sylvain, Correction done

#30 Fix/rightbar icons
  src/components/gameshow/RightBar.jsx
Labels: Sylvain

#32 Fix text size & dropdown ref
  src/components/Navbar.jsx
  src/components/NavbarTools/Dropdown.jsx
  tailwind.config.js
Labels: Sylvain

#31 Feature/redirection genre page
  src/components/Navbar.jsx
Labels: Sylvain

#35 Feature/home carousel new games
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/gameshow/GameShow.jsx
  src/components/genres/Carousel.jsx
  src/components/home/CarouselHome.jsx
  src/components/home/Home.jsx
  src/components/home/HomeNewGames.jsx
  src/components/home/PlatformsList.jsx
  src/components/home/PlatformsLogo.jsx
  src/components/home/Unavoidable.jsx
  src/components/icons/IconPlus.jsx
  src/components/logos/LogoAndroid.jsx
  src/components/logos/LogoIos.jsx
  src/components/logos/LogoNintendo.jsx
  src/components/logos/LogoPc.jsx
  src/components/logos/LogoPlaystation.jsx
  src/components/logos/LogoXbox.jsx
Labels: Sylvain

#39 replace mario in img because someone remove him
  public/images/mario.webp
Labels: Sylvain

#40 Fix/feature/header genre
  src/components/genres/Categories.jsx
  src/components/genres/HeaderGenre.jsx
Labels: Sylvain

#42 Feature/rating box
  public/images/star.svg
  src/components/gameshow/GameShow.jsx
  src/components/gameshow/ProgressBar.jsx
  src/components/gameshow/RatingBox.jsx
Labels: Sylvain

#38 Feature/fix footer
  src/components/Footer.jsx
Labels: Sylvain

#47 Fix gridcard
  package-lock.json
  src/components/genres/CarouselCard.jsx
  src/components/genres/GridCard.jsx
Labels: Sylvain, Correction done

#45 Feature/redirection platform page
  src/components/Navbar.jsx
  src/components/genres/Carousel.jsx
  src/components/genres/Platforms.jsx
  src/router.jsx
Labels: Sylvain
